site_name: xxrjun/cs-resources
site_author: xxrjun

repo_name: cs-resources
repo_url: https://github.com/xxrjun/cs-resources
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: red
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  font:
    code: Roboto Mono
    text: Josefin Sans
  features:
    - content.tabs.link
    - navigation.path
    # - navigation.sections
    
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Toolkits:
    - Development Tools: toolkits/DevelopmentTools.md
    - Daily Tools: toolkits/DailyTools.md
    - Thesis: toolkits/Thesis.md
    - MIS: toolkits/MIS.md
  - Platforms:
    - Youtube Channels: platforms/YoutubeChannels.md
    - GitHub Repositories: platforms/GitHubRepositories.md
    - News: platforms/News.md
  - Fundamentals:
    - Introduction: fundamentals/IntroductionToComputerScience.md
    - Programming Languages: fundamentals/ProgrammingLanguages.md
    - Data Structures and Algorithms: fundamentals/DataStructuresAndAlgorithms.md
    - Computer Networking: fundamentals/ComputerNetworking.md
    # - Operating Systems: fundamentals/OperatingSystems.md
    # - Compilers: fundamentals/Compilers.md
    # - Databases: fundamentals/Databases.md
  - Mathematics:
    - Calculus: mathematics/Calculus.md
    - Linear Algebra: mathematics/LinearAlgebra.md
    # - Discrete Mathematics: mathematics/discrete-mathematics.md
    # - Probability and Statistics: Mathematics/ProbabilityAndStatistics.md
  - Web Development:
    - Beginning: web/Beginning.md
    # - Frontend: web/Frontend.md
    - Backend: web/Backend.md
  # - Machine Learning:
    # - LLM: ml/llm.md
  # - Software Engineering: SoftwareEngineering.md 
  - Specialized Fields:
    # - Data Science: specialized-fields/data-science.md
    # - Quantum Computing: specialized-fields/quantum-computing.md
    # - DevOps: specialized-fields/devops.md
  - Career:
    - Graduate Entrance Examination: careers/graduate-entrance-examination.md
    - Interview Preparation: careers/Interview.md
    # - Resume and Portfolio: careers/resume-and-portfolio.md
  - My Setup: MySetup.md
  # - About Me: AboutMe.md

extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright &copy; 2023 - present, xxrjun, All rights reserved.

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: xxrjun/cs-resources
      branch: main