name: Generate Link Status Report

on:
  push:
    branches:
      - main

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
      - name: Generate link status report
        run: python ./utils/link_status_report.py
      - name: Deploy link status report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./
          keep_files: true